### ISSUE TITLE
Not working with wine 

### ISSUE THREAD

**Issue by malik8118** [mjishnu/alt-app-installer#53]
user1@Malik:~/git/alt-app-installer/app$ wine python3 main.py
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.
This  is the issue i face with wine
Am a total beginner as well

**Comment by mjishnu** [comment]
hey, sorry but you can't run the exe provided in releases using wine. as a workaround build it using source. tho note that you cant obviously install the apps since the apis need for that doesn't exist in linux. but you can download the appx files  using download mode in options of alt app installer and figure out ways to run the appx. you can get the guide for building from source in readme
