### ISSUE TITLE
Suggestion: New message for failed to install dependency

### ISSUE THREAD

**Issue by uuc110** [mjishnu/alt-app-installer#55]
its come to my attentino that whenever I reinstall the app, which was previously installed , and then reinstall from alt app installer it hows "Failed to install dependency" yea ofc since its already installed, since its already available in system when installed previously. 
So, I was thinking for a UX purpose, I'm suggesting that it should say "Depndency already installed" or "Dependancy already satisfied" which will give better explanation.

**Comment by mjishnu** [comment]
if you click show details, it should give a better message. this is because in some cases the dependencies are not install cause some resource need by it is currently in use, i just made a generic warning msg at the time. the current implementation doesn't check if dependencies are installed or the scenario i mentioned earlier happened.

i am planning on rewriting the program from scratch in c#. so i won't be adding much new features to this at the moment. but if you are someone reading this is willing to implement it be sure to make a PR.

**Comment by uuc110** [comment]
okay I will look into the code If I find a better way or optimized apporach to do this, then I will surely PR some good effective changes
