### ISSUE TITLE
No apps downloaded seems to install properly

### ISSUE THREAD

**Issue by DuckersMcQuack** [mjishnu/alt-app-installer#61]
App downloader kept erroring with "dependencies couldn't be installed"

And when i launch the downloaded apps, they crash/freeze.

This is the app i try to download, as for some reason, install button is greyed out/not loading "install" button for me. So i'm trying to offline the entire thing.
https://apps.microsoft.com/detail/9wzdncrfj3t6?hl=en-ms&gl=MS

![image](https://github.com/mjishnu/alt-app-installer/assets/9039370/841a0372-2446-494c-9fe2-6b994eecfbd1)

**Comment by mjishnu** [comment]
I think it is due to dependencies issue, try enable ignore version flag for dependencies
![Screenshot 2024-06-22 222908](https://github.com/mjishnu/alt-app-installer/assets/83004520/ac4e2939-437a-4d10-a27d-742df703f184)
![image](https://github.com/mjishnu/alt-app-installer/assets/83004520/fc5f4fb8-bb06-4fdf-b436-e777fa11cf39)

if this is not working please send log file.
